export const planetsData = {
  Mercury: {
    description: `Mercury is the smallest planet in the Solar System and the closest to the Sun. Its orbit around the Sun takes 87.97 Earth days, the shortest of all the Sun's planets. `,
    distance_from_sun: '0.39ua',
    gravity: '3,7 m/s²',
    mass: '3,28·10^23',
    mean_temperature: '160 ºC',
    length_of_day: '1408h',
    number_of_moons: '0',
  },
  Venus: {
    description: `Venus is the second planet from the Sun. It is named after the Roman goddess of love and beauty. As the brightest natural object in Earth's night sky after the Moon, Venus can cast shadows and can be, on rare occasions, visible to the naked eye in broad daylight.`,
    distance_from_sun: '0.72ua',
    gravity: '8,87 m/s²',
    mass: '4,83·10^24',
    mean_temperature: '465 ºC',
    length_of_day: '5832h',
    number_of_moons: '0',
  },
  Earth: {
    description: `Earth is the third planet from the Sun and the only astronomical object known to harbor and support life. About 29.2% of Earth's surface is land consisting of continents and islands.`,
    distance_from_sun: '1ua',
    gravity: '9,8 m/s²',
    mass: '5,98·10^24',
    mean_temperature: '15 ºC',
    length_of_day: '24h',
    number_of_moons: '1',
  },
  Mars: {
    description: `Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System, being larger than only Mercury. In English, Mars carries the name of the Roman god of war and is often referred to as the "Red Planet". `,
    distance_from_sun: '1.52ua',
    gravity: '3,71 m/s²',
    mass: '6,40·10^23',
    mean_temperature: '-80ºC',
    length_of_day: '25h',
    number_of_moons: '2',
  },
  Jupiter: {
    description: `Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass more than two and a half times that of all the other planets in the Solar System combined, but slightly less than one-thousandth the mass of the Sun. `,
    distance_from_sun: '5.20ua',
    gravity: '24,79 m/s²',
    mass: '1,90·10^27',
    mean_temperature: '-20ºC',
    length_of_day: '10h',
    number_of_moons: '63',
  },
  Saturn: {
    description: `Saturn is the sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is a gas giant with an average radius of about nine and a half times that of Earth. `,
    distance_from_sun: '9.54ua',
    gravity: '10,44 m/s²',
    mass: '5,98·10^26',
    mean_temperature: '-160ºC',
    length_of_day: '11h',
    number_of_moons: '62',
  },
  Uranus: {
    description: `Uranus is the seventh planet from the Sun. Its name is a reference to the Greek god of the sky, Uranus, who, according to Greek mythology, was the great-grandfather of Ares (Mars), grandfather of Zeus (Jupiter) and father of Cronus (Saturn).`,
    distance_from_sun: '19.19ua',
    gravity: '8,87 m/s²',
    mass: '8,67·10^25',
    mean_temperature: '-205 ºC',
    length_of_day: '17h',
    number_of_moons: '27',
  },
  Neptune: {
    description: `Neptune is the eighth and farthest known Solar planet from the Sun. In the Solar System, it is the fourth-largest planet by diameter, the third-most-massive planet, and the densest giant planet. It is 17 times the mass of Earth, slightly more massive than its near-twin Uranus.`,
    distance_from_sun: '30.06ua',
    gravity: '11,15 m/s²',
    mass: '1,05·10^26',
    mean_temperature: '-218 ºC',
    length_of_day: '16h',
    number_of_moons: '13',
  },
}
